server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: flog
      pipeline_stages:
          - json:
                expressions:
                    output: referrer
                    timestamp: datetime
                    user: '"user-identifier"'
                    status: status
                    method: method
          - labels:
                user:
                status:
                method:
          - timestamp:
                source: timestamp
                format: '02/Jan/2006:15:04:05 -0700'
          - output:
                source: output
      static_configs:
          - targets:
                - localhost
            labels:
                job: flog
                __path__: /var/log/flog.log
